version: "1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env:
      NODE_ENV: production
    healthcheck:
      path: /api/providers
      interval: 30s
